image: gradle:alpine

before_script:
  - cd newsProject  # newsProject 디렉토리로 이동
  - GRADLE_USER_HOME="$(pwd)/.gradle"  # .gradle 경로를 newsProject 디렉토리 내로 설정
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build  # 경로가 newsProject/build로 자동으로 설정됨
      - .gradle  # 경로가 newsProject/.gradle로 자동으로 설정됨

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build  # 경로가 newsProject/build로 자동으로 설정됨
      - .gradle  # 경로가 newsProject/.gradle로 자동으로 설정됨

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
